#!/usr/bin/env python

import sys
from optparse import OptionParser
import requests


class PulpConn(object):
    """
    Pulp connector class
    """

    def __init__(self, username, password, server):
        self.username = username
        self.password = password
        self.server = server

    def get_tasks(self):
        """
        Retrieves the PULP tasks
        """

        url = "https://%s/%s" % (self.server, '/pulp/api/v2/tasks/')
        r = requests.get(url, auth=(self.username, self.password), verify=False)

        return r.json()


if __name__ == '__main__':
    # parse command line
    parser = OptionParser()
    parser.add_option('-u', '--username', dest='username', help='PULP API username')
    parser.add_option('-p', '--password', dest='password', help='PULP API password')
    parser.add_option('-s', '--server', dest='server', help='PULP API server')
    parser.set_usage('%prog [options]')
    (options, args) = parser.parse_args()

    if not options.username or not options.password or not options.server:
        parser.print_help()
        sys.exit(1)

    # get tasks from the server
    pulp_conn = PulpConn(options.username, options.password, options.server)
    tasks = pulp_conn.get_tasks()

    # get running and waiting tasks
    running = waiting = 0
    for task in tasks:
        state = task.get('state', '')
        if state == 'running':
            running += 1
        elif state == 'waiting':
            waiting += 1

    # print result
    print "running: %d, waiting: %d" % (running, waiting)
